FROM tomcat:8.5.31-jre8-slim

MAINTAINER rodick.h <rodick@ehanlin.com.tw>

RUN apt-get update && apt-get install -y wget vim && \
    mkdir -p /opt/cprof && wget -q -O- https://storage.googleapis.com/cloud-profiler/java/latest/profiler_java_agent.tar.gz | tar xzv -C /opt/cprof && \
    ln -sf /usr/share/zoneinfo/Asia/Taipei /etc/localtime && echo "Asia/Taipei" > /etc/timezone && \
    rm -rf ${CATALINA_HOME}/webapps/* /var/lib/apt/lists/* 

COPY basetomcat/ ${CATALINA_HOME}/

